version: 1.1.{build}
configuration: Release
platform: x64
environment:
  CodeAnalysisTreatWarningsAsErrors: true
  LinecoverageThreshold: 1
  AutomationLinecoverageThreshold: 70
before_build:
- ps: nuget restore MediaStreamer\MediaStreamer.sln
build:
  project: MediaStreamer\MediaStreamer.sln
  verbosity: minimal
test_script:
- ps: .\appveyor_tests.ps1
artifacts:
- path: artifacts/h264_320x240_sample.zip
  name: video_sample
- path: MediaStreamer/MediaStreamer.UI/bin/$(CONFIGURATION)
  name: app
- path: MediaStreamer/MediaStreamer.AutomationTests/bin/$(CONFIGURATION)
  name: automation_test
deploy: off