// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace BJ
{
    using System.CodeDom.Compiler;
    using System.Drawing;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;


    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// ClickCallButton
        /// </summary>
        public void ClickCallButton()
        {
            #region Variable Declarations
            WpfButton uIItemButton = this.UIMainWindowWindow1.UIItemButton;
            #endregion

            // Click button numbered 4 in 'MainWindow' window
            Mouse.Click(uIItemButton, new Point(17, 38));
        }
        
        /// <summary>
        /// ClickOnTitleBar
        /// </summary>
        public void ClickOnTitleBar()
        {
            #region Variable Declarations
            WinTitleBar uIMainWindowTitleBar = this.UIMediaStreamerUIMainWWindow.UIMediaStreamerUIMainWTitleBar;
            #endregion

            // Click 'MainWindow' title bar
            Mouse.Click(uIMainWindowTitleBar, new Point(906, 11));
        }
        
        /// <summary>
        /// CloseApp
        /// </summary>
        public void CloseApp()
        {
            #region Variable Declarations
            WinButton uICloseButton = this.UIMediaStreamerUIMainWWindow.UICloseButton;
            #endregion

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(36, 11));
        }
   
        /// <summary>
        /// RestoreFromTaskBar
        /// </summary>
        public void RestoreFromTaskBar()
        {
            #region Variable Declarations
            WinButton uIDesktopList = this.UIProgramManagerWindow.UIFolderToolBar.UIDesktopToolBarButton;
            #endregion

            // Click 'Desktop' list box
            Mouse.Click(uIDesktopList, new Point(3391, 220));
        }
        
        
       
       
        
        public UIProgramRunningApplication UIProgramManagerWindow
        {
            get
            {
                if ((this.mUIProgramManagerWindow == null))
                {
                    this.mUIProgramManagerWindow = new UIProgramRunningApplication();
                }
                return this.mUIProgramManagerWindow;
            }
        }
        
                
        public UIMainWindowWindow UIMainWindowWindow1
        {
            get
            {
                if ((this.mUIMainWindowWindow1 == null))
                {
                    this.mUIMainWindowWindow1 = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow1;
            }
        }
        
        public UIMediaStreamerUIMainWWindow UIMediaStreamerUIMainWWindow
        {
            get
            {
                if ((this.mUIMediaStreamerUIMainWWindow == null))
                {
                    this.mUIMediaStreamerUIMainWWindow = new UIMediaStreamerUIMainWWindow();
                }
                return this.mUIMediaStreamerUIMainWWindow;
            }
        }
        
                        
        private UIProgramRunningApplication mUIProgramManagerWindow;
               
        private UIMainWindowWindow mUIMainWindowWindow1;
        
        private UIMediaStreamerUIMainWWindow mUIMediaStreamerUIMainWWindow;
      
    }
    
   
      
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIProgramRunningApplication : WinWindow
    {
        
        public UIProgramRunningApplication()
        {
            #region Search Criteria
            this.SearchProperties.Add(UITestControl.PropertyNames.ClassName, "MSTaskSwWClass");
            this.SearchProperties.Add(UITestControl.PropertyNames.Name, "Running applications");
            this.WindowTitles.Add("Running applications");
            #endregion
        }
        
        #region Properties
        public UIFolderToolBar UIFolderToolBar
        {
            get
            {
                if ((this.mUIFolderToolBar == null))
                {
                    this.mUIFolderToolBar = new UIFolderToolBar();
                }
                return this.mUIFolderToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIFolderToolBar mUIFolderToolBar;


        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIFolderToolBar : WinToolBar
    {
        
        public UIFolderToolBar()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MSTaskListWClass";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Running applications";

            this.WindowTitles.Add("Running applications");
            #endregion
        }
        
        #region Properties
        public WinButton UIDesktopToolBarButton
        {
            get
            {
                if ((this.mUIDesktopToolBar == null))
                {
                    this.mUIDesktopToolBar = new WinButton(this);
                    #region Search Criteria
                    this.mUIDesktopToolBar.SearchProperties[WinButton.PropertyNames.Name] = "MediaStreamer.UI - MainWindow";
                    this.mUIDesktopToolBar.WindowTitles.Add("Running applications");
                    #endregion
                }
                return mUIDesktopToolBar;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIDesktopToolBar;
        #endregion
    }
    
        
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MediaStreamer.UI - Toolbar";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MediaStreamer.UI - Toolbar");
            #endregion
        }

        #region Properties
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIStartStopButtonButton == null))
                {
                    this.mUIStartStopButtonButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIStartStopButtonButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "StartStopButton";
                    this.mUIStartStopButtonButton.WindowTitles.Add("MediaStreamer.UI - Toolbar");
                    #endregion
                }
                return this.mUIStartStopButtonButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIStartStopButtonButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMediaStreamerUIMainWWindow : WinWindow
    {
        
        public UIMediaStreamerUIMainWWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MediaStreamer.UI - MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MediaStreamer.UI - MainWindow");
            #endregion
        }
        
        #region Properties
        public WinTitleBar UIMediaStreamerUIMainWTitleBar
        {
            get
            {
                if ((this.mUIMediaStreamerUIMainWTitleBar == null))
                {
                    this.mUIMediaStreamerUIMainWTitleBar = new WinTitleBar(this);
                    #region Search Criteria
                    this.mUIMediaStreamerUIMainWTitleBar.WindowTitles.Add("MediaStreamer.UI - MainWindow");
                    #endregion
                }
                return this.mUIMediaStreamerUIMainWTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private WinTitleBar mUIMediaStreamerUIMainWTitleBar;
        private WinButton mUIMinimizeButton;
        private WinButton mUICloseButton;
        #endregion

        public WinButton UIMinimizeButton
        {
            get
            {
                if ((this.mUIMinimizeButton == null))
                {
                    this.mUIMinimizeButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIMinimizeButton.SearchProperties[WinButton.PropertyNames.Name] = "Minimize";
                    this.mUIMinimizeButton.WindowTitles.Add("MediaStreamer.UI - MainWindow");
                    #endregion
                }
                return this.mUIMinimizeButton;
            }
        }

        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("MediaStreamer.UI - MainWindow");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }

        public class UIRunningapplicationsWindow : WinWindow
        {

            public UIRunningapplicationsWindow()
            {
                #region Search Criteria
                this.SearchProperties[WinWindow.PropertyNames.Name] = "Running applications";
                this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MSTaskSwWClass";
                this.WindowTitles.Add("Running applications");
                #endregion
            }

            #region Properties
            public UIRunningapplicationsToolBar UIRunningapplicationsToolBar
            {
                get
                {
                    if ((this.mUIRunningapplicationsToolBar == null))
                    {
                        this.mUIRunningapplicationsToolBar = new UIRunningapplicationsToolBar(this);
                    }
                    return this.mUIRunningapplicationsToolBar;
                }
            }
            #endregion

            #region Fields
            private UIRunningapplicationsToolBar mUIRunningapplicationsToolBar;
            #endregion
        }

        [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
        public class UIRunningapplicationsToolBar : WinToolBar
        {

            public UIRunningapplicationsToolBar(UITestControl searchLimitContainer) :
                    base(searchLimitContainer)
            {
                #region Search Criteria
                this.SearchProperties[WinToolBar.PropertyNames.Name] = "Running applications";
                this.WindowTitles.Add("Running applications");
                #endregion
            }

            #region Properties
            public WinButton UIMediaStreamerUIMainWButton
            {
                get
                {
                    if ((this.mUIMediaStreamerUIMainWButton == null))
                    {
                        this.mUIMediaStreamerUIMainWButton = new WinButton(this);
                        #region Search Criteria
                        this.mUIMediaStreamerUIMainWButton.SearchProperties[WinButton.PropertyNames.Name] = "MediaStreamer.UI - MainWindow";
                        this.mUIMediaStreamerUIMainWButton.WindowTitles.Add("Running applications");
                        #endregion
                    }
                    return this.mUIMediaStreamerUIMainWButton;
                }
            }
            #endregion

            #region Fields
            private WinButton mUIMediaStreamerUIMainWButton;
            #endregion
        }
    }
}
